// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://svuwldxhgifuctfehfao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2dXdsZHhoZ2lmdWN0ZmVoZmFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjM4NzEsImV4cCI6MjA2OTk5OTg3MX0.sAibazfgoCw06QJQqfDvBZUQUU4WxFGAyxQyCiYMhkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);